export const AUTH_COUNTRIES = Object.freeze([
  {
    iso2: 'JO',
    dialCode: '+962',
    flag: 'JO',
    nameKey: 'auth.countries.jordan',
    minLength: 9,
    maxLength: 9,
    stripLeadingZero: true,
  },
  {
    iso2: 'SA',
    dialCode: '+966',
    flag: 'SA',
    nameKey: 'auth.countries.saudi',
    minLength: 9,
    maxLength: 9,
    stripLeadingZero: true,
  },
  {
    iso2: 'AE',
    dialCode: '+971',
    flag: 'AE',
    nameKey: 'auth.countries.uae',
    minLength: 9,
    maxLength: 10,
    stripLeadingZero: true,
  },
  {
    iso2: 'KW',
    dialCode: '+965',
    flag: 'KW',
    nameKey: 'auth.countries.kuwait',
    minLength: 8,
    maxLength: 8,
    stripLeadingZero: false,
  },
  {
    iso2: 'QA',
    dialCode: '+974',
    flag: 'QA',
    nameKey: 'auth.countries.qatar',
    minLength: 8,
    maxLength: 8,
    stripLeadingZero: false,
  },
  {
    iso2: 'EG',
    dialCode: '+20',
    flag: 'EG',
    nameKey: 'auth.countries.egypt',
    minLength: 10,
    maxLength: 10,
    stripLeadingZero: true,
  },
  {
    iso2: 'PS',
    dialCode: '+970',
    flag: 'PS',
    nameKey: 'auth.countries.palestine',
    minLength: 9,
    maxLength: 9,
    stripLeadingZero: true,
  },
  {
    iso2: 'US',
    dialCode: '+1',
    flag: 'US',
    nameKey: 'auth.countries.unitedStates',
    minLength: 10,
    maxLength: 10,
    stripLeadingZero: false,
  },
  {
    iso2: 'GB',
    dialCode: '+44',
    flag: 'GB',
    nameKey: 'auth.countries.unitedKingdom',
    minLength: 10,
    maxLength: 10,
    stripLeadingZero: true,
  },
]);

export const DEFAULT_AUTH_COUNTRY_CODE = '+962';
